[package]
name = "exsomnis-core"
version = "0.0.0"
edition = "2024"
rust-version = "1.93"
publish = false

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
napi = { version = "3", default-features = false, features = ["napi4", "dyn-symbols"] }
napi-derive = { version = "3", default-features = false, features = ["type-def", "strict"] }

[build-dependencies]
napi-build = "2"
