/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Screen {
  constructor(cols: number, rows: number)
  resize(cols: number, rows: number): void
  setCapabilities(flags: number): void
  invalidate(): void
  present(ops: Int32Array, opCount: number, text: Uint8Array, textLen: number): number
  takeStats(): FrameStats
  shutdown(): void
}

export declare function cellWidth(text: string): number

export declare function coreVersion(): string

export interface DiffDocument {
  files: Array<DiffFile>
}

export interface DiffFile {
  oldPath: string
  newPath: string
  status: DiffStatus
  binary: boolean
  additions: number
  deletions: number
  hunks: Array<DiffHunk>
}

export interface DiffHunk {
  header: string
  oldStart: number
  oldCount: number
  newStart: number
  newCount: number
  lines: Array<DiffLine>
}

export interface DiffLine {
  kind: DiffLineKind
  text: string
  oldLineNumber?: number
  newLineNumber?: number
}

export declare const enum DiffLineKind {
  Context = 'context',
  Added = 'added',
  Removed = 'removed',
  NoNewline = 'noNewline'
}

export declare const enum DiffStatus {
  Added = 'added',
  Modified = 'modified',
  Deleted = 'deleted',
  Renamed = 'renamed'
}

export interface FrameStats {
  frames: number
  drawMicrosMean: number
  drawMicrosP95: number
  diffMicrosMean: number
  diffMicrosP95: number
  writeMicrosMean: number
  writeMicrosP95: number
  bytesMean: number
  bytesMax: number
  bytesTotal: number
  cellsTotal: number
}

export declare function parseUnifiedDiff(text: string): DiffDocument
