/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Screen {
  constructor(cols: number, rows: number)
  resize(cols: number, rows: number): void
  setCapabilities(flags: number): void
  invalidate(): void
  present(ops: Int32Array, opCount: number, text: Uint8Array, textLen: number): number
  takeStats(): FrameStats
  shutdown(): void
}

export declare function cellWidth(text: string): number

export declare function coreVersion(): string

export interface FrameStats {
  frames: number
  drawMicrosMean: number
  drawMicrosP95: number
  diffMicrosMean: number
  diffMicrosP95: number
  writeMicrosMean: number
  writeMicrosP95: number
  bytesMean: number
  bytesMax: number
  bytesTotal: number
  cellsTotal: number
}
